-- 1. 수집 뉴스 기사 테이블 (news_articles)
CREATE TABLE IF NOT EXISTS news_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    url TEXT UNIQUE NOT NULL,
    source VARCHAR(100),
    category VARCHAR(50) NOT NULL, -- '비트코인', '세계경제', '국내경제'
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 에이전트 요약 보고서 테이블 (agent_reports)
CREATE TABLE IF NOT EXISTS agent_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date DATE NOT NULL,
    category VARCHAR(50) NOT NULL, -- '비트코인', '세계경제', '국내경제', '종합'
    summary TEXT NOT NULL,         -- '원인-대책-결과'의 논리적 요약
    risk_score INT DEFAULT 50,     -- 0 ~ 100 리스크 지수
    keywords TEXT[],               -- 핵심 키워드 배열
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (report_date, category) -- 동일 날짜, 카테고리의 보고서는 유일하게 존재
);

-- 인덱스 설정 (빠른 검색 및 중복 검사용)
CREATE INDEX IF NOT EXISTS idx_news_category ON news_articles(category);
CREATE INDEX IF NOT EXISTS idx_news_url ON news_articles(url);
CREATE INDEX IF NOT EXISTS idx_report_date_category ON agent_reports(report_date, category);
